//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên tài khoản")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Tên ảnh tài khoản không được ít hơn 1 ký tự và nhiều hơn 100 ký tự")]
        public string username { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        public string password { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Số điện thoại phải là 10 ký tự")]
        public string phone { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên người dùng")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Tên người dùng không được ít hơn 5 ký tự và nhiều hơn 50 ký tự")]
        public string fullname { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn loại người dùng")]
        public Nullable<int> UserTypeID { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
